version: "3"
services:
  node-hiprint-pdf:
    image: node-hiprint-pdf:1.0.0
    restart: always
    container_name: node-hiprint-pdf
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT:-3001}
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
